spring:
  profiles: home
  application:
    name: multi-datasource
  datasource:
    ds1:
      jdbc-url: jdbc:mysql://192.168.0.99:3306/people?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Hongkong
      username: root
      password: mysql
      driverClassName: com.mysql.cj.jdbc.Driver
    ds2:
      jdbc-url: jdbc:mysql://192.168.0.99:3306/people?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Hongkong
      username: root
      password: mysql
      driverClassName: com.mysql.cj.jdbc.Driver
    ds3:
      jdbc-url: jdbc:mysql://192.168.0.99:3306/people?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Hongkong
      username: root
      password: mysql
      driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mybatis/*/*.xml
  type-aliases-package: org.leesia.entity